# Generated by Django 5.2.1 on 2026-05-28 18:44

import django.core.validators
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0002_product_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=200, verbose_name='اسم صاحب الحيوان')),
                ('phone', models.CharField(max_length=100, verbose_name='رقم الهاتف')),
                ('pet_name', models.CharField(max_length=200, verbose_name='اسم الحيوان')),
                ('pet_type', models.CharField(choices=[('cat', 'قط'), ('dog', 'كلب')], max_length=30, verbose_name='نوع الحيوان')),
                ('treatment_type', models.CharField(choices=[('with_treatment', 'مع علاج'), ('without_treatment', 'بدون علاج')], default='without_treatment', max_length=30, verbose_name='العلاج')),
                ('check_in', models.DateTimeField(default=django.utils.timezone.now, verbose_name='وقت الدخول')),
                ('check_out', models.DateTimeField(blank=True, null=True, verbose_name='وقت الخروج')),
                ('daily_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='سعر المبيت اليومي')),
                ('treatment_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='سعر العلاج')),
                ('total_days', models.PositiveIntegerField(default=1, verbose_name='عدد الأيام')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='المبلغ النهائي')),
                ('status', models.CharField(choices=[('inside', 'داخل العيادة'), ('checked_out', 'تم الخروج')], default='inside', max_length=30, verbose_name='الحالة')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
